// src/entrypoints/content/modules/preview/components/frame/frameVotes.vue
<template>
    <div class="refresher-preview-votes">
        <div>
            <PreviewButton
                id="upvote"
                :click="upvote"
                :text="upvoteText"
                class="refresher-upvote"
            />
            <PreviewButton
                v-if="!disabledDownvote"
                id="downvote"
                :click="downvote"
                :text="downvotes ?? 'X'"
                class="refresher-downvote"
            />
            <PreviewButton
                id="share"
                :click="share"
                class="refresher-share"
            />
            <PreviewButton
                id="newtab"
                :click="original"
            />
        </div>
    </div>
</template>

<script lang="ts" setup>
import {computed} from "vue";

import PreviewButton from "@/components/previewButton.vue";

interface Props {
    upvotes?: string;
    fixedUpvotes?: string;
    downvotes?: string;
    disabledDownvote?: boolean;
    upvote: () => Promise<boolean>;
    downvote: () => Promise<boolean>;
    share: () => Promise<boolean>;
    original: () => Promise<boolean>;
}

const props = defineProps<Props>();

const upvoteText = computed(() => {
    const base = props.upvotes ?? "X";
    return props.fixedUpvotes === undefined ? base : `${base} (${props.fixedUpvotes})`;
});
</script>

<style lang="scss" scoped>
.refresher-preview-votes {
    display: flex;
    margin-top: 2.5vh;
    position: relative;

    & > div {
        display: flex;
        margin: auto;
    }
}
</style>

// src/entrypoints/content/modules/preview/components/frame/frameVotes.tsx
import PreviewButton from "@/components/previewButton";

import "./frameVotes.scss";

interface Props {
    upvotes?: string;
    fixedUpvotes?: string;
    downvotes?: string;
    disabledDownvote?: boolean;
    upvote: () => Promise<boolean>;
    downvote: () => Promise<boolean>;
    share: () => Promise<boolean>;
    original: () => Promise<boolean>;
}

export default function FrameVotes({
    upvotes,
    fixedUpvotes,
    downvotes,
    disabledDownvote,
    upvote,
    downvote,
    share,
    original
}: Props) {
    const base = upvotes ?? "X";
    const upvoteText = fixedUpvotes === undefined ? base : `${base} (${fixedUpvotes})`;

    return (
        <div className="refresher-preview-votes">
            <div>
                <PreviewButton
                    click={upvote}
                    className="refresher-upvote"
                    id="upvote"
                    text={upvoteText}
                />
                {!disabledDownvote && (
                    <PreviewButton
                        click={downvote}
                        className="refresher-downvote"
                        id="downvote"
                        text={downvotes ?? "X"}
                    />
                )}
                <PreviewButton
                    click={share}
                    className="refresher-share"
                    id="share"
                />
                <PreviewButton
                    click={original}
                    id="newtab"
                />
            </div>
        </div>
    );
}
