// src/core/frameComponent.vue
<template>
  <div
      v-show="!closed"
      :class="{
            background: background,
            blur: blur,
            fadeIn: fade,
            fadeOut: !fade,
            stack: fade
        }"
      class="refresher-frame-outer"
  >
    <div
        ref="groupElement"
        class="refresher-group"
        @click="clickHandle"
        @wheel="wheelHandle"
    >
      <RefresherFrame
          v-if="frames[0]"
          ref="bodyFrameRef"
          :frame="frames[0]"
          :index="0"
      />
      <RefresherFrame
          v-if="frames[1]"
          ref="commentFrameRef"
          :frame="frames[1]"
          :index="1"
      />

      <div id="scroll">
        <img
            :src="getAssetURL('upvote')"
            @click="() => clickScroll('up')"
        />
        <img
            :src="getAssetURL('downvote')"
            @click="() => clickScroll('down')"
        />
      </div>
    </div>
    <transition name="refresher-prev-post">
      <RefresherScroll
          v-if="scrollModeTop"
          side="top"
      />
    </transition>
    <transition name="refresher-next-post">
      <RefresherScroll
          v-if="scrollModeBottom"
          side="bottom"
      />
    </transition>
  </div>
</template>

<script lang="ts" setup>
import {onBeforeUnmount, onMounted, provide, ref, watch} from "vue";

import RefresherFrame from "../components/frame.vue";
import {getAssetURL} from "../utils/assetURL";
import RefresherScroll from "../components/scroll.vue";
import type {PreviewFrame} from "./PreviewFrame";
import type {FrameStackOption} from "./frame";

interface Props {
  frames: PreviewFrame[];
  option?: FrameStackOption;
}

const props = withDefaults(defineProps<Props>(), {
  option: () => ({})
});

const emit = defineEmits<{
  close: [];
}>();

const fade = ref(false);
const scrollModeTop = ref(false);
const scrollModeBottom = ref(false);
const closed = ref(false);
const inputFocus = ref(false);
const groupElement = ref<HTMLElement>();
const bodyFrameRef = ref<{ incrementCommentKey?: () => void } | null>(null);
const commentFrameRef = ref<{ incrementCommentKey?: () => void } | null>(null);
let fadeOutTimer: number | null = null;

provide("refresherInputFocus", inputFocus);

const background = ref(props.option?.background ?? false);
const blur = ref(props.option?.blur ?? false);
const onScroll = props.option?.onScroll;

watch(closed, (val: boolean) => {
  document.body.style.overflow = val ? "" : "hidden";
});

const onKeyUp = (ev: KeyboardEvent) => {
  if (ev.code === "Escape" && !closed.value) {
    outerClick();
  }
};

const clickScroll = (type: "up" | "down") => {
  if (!groupElement.value) return;
  const y = type === "up" ? 0 : groupElement.value.scrollHeight;
  groupElement.value.scroll(0, y);
};

const clickHandle = (ev: MouseEvent) => {
  if (ev.target !== groupElement.value) return;

  const selection = window.getSelection();
  if (selection && selection.toString().length !== 0) return;

  outerClick();
};

const wheelHandle = (ev: WheelEvent) => {
  if (typeof onScroll === "function") {
    onScroll(ev, groupElement.value as HTMLElement);
  }
};

const setScrollMode = (mode: "top" | "bottom" | "none") => {
  scrollModeTop.value = mode === "top";
  scrollModeBottom.value = mode === "bottom";
};

const clearScrollMode = () => setScrollMode("none");

const outerClick = () => {
  props.frames.forEach((frame) => frame.emitClose());
  emit("close");
  fadeOut();
};

const fadeIn = () => {
  fade.value = true;
  closed.value = false;
};

const fadeOut = () => {
  fade.value = false;

  if (fadeOutTimer !== null) {
    window.clearTimeout(fadeOutTimer);
  }

  fadeOutTimer = window.setTimeout(() => {
    closed.value = true;
    fadeOutTimer = null;
  }, 251);
};

const close = () => outerClick();

const onClose = (handler: () => void) => {
  props.frames.forEach((frame) => frame.onClose(handler));
};

onMounted(() => {
  document.body.style.overflow = "hidden";
  document.addEventListener("keyup", onKeyUp);
});

onBeforeUnmount(() => {
  document.removeEventListener("keyup", onKeyUp);
  document.body.style.overflow = "";

  if (fadeOutTimer !== null) {
    window.clearTimeout(fadeOutTimer);
    fadeOutTimer = null;
  }
});

watch(closed, (value) => {
  if (value) {
    props.frames.forEach((frame) => frame.emitClose());
  }
});

defineExpose({
  frames: props.frames,
  fade,
  scrollModeTop,
  scrollModeBottom,
  closed,
  inputFocus,
  groupElement,
  bodyFrameRef,
  commentFrameRef,
  body: () => props.frames[0],
  comment: () => props.frames[1],
  setScrollMode,
  clearScrollMode,
  outerClick,
  close,
  fadeIn,
  fadeOut,
  onClose
});
</script>

<style lang="scss">
@use "@/assets/styles/variables" as *;

.refresher-frame-outer {
  display: flex;
  left: 0;
  margin: 0;
  min-height: 100%;
  opacity: 0;
  overflow: hidden;
  position: fixed;
  top: 0;
  width: 100%;
  z-index: $z-tooltip;

  &.background {
    background-color: var(--refresher-bg-overlay);
  }

  &.blur {
    backdrop-filter: blur(5px) saturate(150%);
  }

  &.center {
    align-items: center;
    justify-content: center;
  }

  &.fadeIn {
    opacity: 1;
    transition: 0.6s opacity $ease-out-expo;

    .refresher-frame {
      transform: translateY(0px);
      transition: 0.5s transform $ease-out-expo;
    }
  }

  &.fadeOut {
    opacity: 0;
    pointer-events: none;
    transition: 0.25s opacity $ease-out-expo;

    .refresher-frame {
      transform: translateY(10px);
      transition: 0.25s transform $ease-out-expo;
    }
  }

  &.stack {
    display: block;
    min-height: 100%;
  }
}

.refresher-group {
  display: block;
  height: 100%;
  overflow-y: auto;
  overscroll-behavior: contain;
  position: absolute;
  width: 100%;
}

#scroll {
  bottom: 5px;
  display: grid;
  position: fixed;
  right: 0;
  user-select: none;
  width: 100px;
  z-index: $z-tooltip;
}
</style>

// src/entrypoints/content/modules/preview/components/frame/frameComponent.tsx
import {ChevronDown, ChevronUp} from "lucide-react";
import {createContext, useEffect, useRef, useState} from "react";
import type {FrameScrollApi, FrameStackOption, PreviewFrame} from "../../frame";

import Frame from "./frame";
import ScrollIndicator from "./scroll";

import "./frameComponent.scss";

// 댓글 입력 포커스 상태 공유 (write_comment가 소비)
export const InputFocusContext = createContext<{ current: boolean }>({current: false});

interface Props {
    frames: PreviewFrame[];
    option?: FrameStackOption;
    apiRef: { current: FrameScrollApi | null };
}

export default function FrameComponent({frames, option = {}, apiRef}: Props) {
    const [scrollModeTop, setScrollModeTop] = useState(false);
    const [scrollModeBottom, setScrollModeBottom] = useState(false);
    const [closed, setClosed] = useState(false);

    const groupElement = useRef<HTMLDivElement>(null as unknown as HTMLDivElement);
    const commentFrameRef = useRef<{ incrementCommentKey?: () => void } | null>(null);
    const inputFocus = useRef(false);

    // 마운트 후 바뀌지 않는 옵션이므로 반응형 불필요
    const background = option?.background ?? false;
    const blur = option?.blur ?? false;
    const onScroll = option?.onScroll;

    const closedRef = useRef(false);
    closedRef.current = closed;

    // 페이드 전환 (fade/closed, body overflow, timer 관리)
    const [fade, setFade] = useState(false);
    const fadeOutTimer = useRef<number | null>(null);

    useEffect(() => {
        document.body.style.overflow = "hidden";
        document.addEventListener("keyup", onKeyUp);
        return () => {
            document.removeEventListener("keyup", onKeyUp);
        };
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    useEffect(() => {
        document.body.style.overflow = closed ? "" : "hidden";
        if (closed) frames.forEach((frame) => frame.emitClose());
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [closed]);

    useEffect(() => {
        return () => {
            document.body.style.overflow = "";
            if (fadeOutTimer.current !== null) {
                window.clearTimeout(fadeOutTimer.current);
                fadeOutTimer.current = null;
            }
        };
    }, []);

    const fadeIn = () => {
        setFade(true);
        setClosed(false);
    };

    const fadeOut = () => {
        setFade(false);

        if (fadeOutTimer.current !== null) {
            window.clearTimeout(fadeOutTimer.current);
        }

        fadeOutTimer.current = window.setTimeout(() => {
            setClosed(true);
            fadeOutTimer.current = null;
        }, 251);
    };

    useEffect(() => {
        fadeIn();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    const close = () => {
        fadeOut();
    };

    const onKeyUp = (ev: KeyboardEvent) => {
        if (ev.code === "Escape" && !closedRef.current) {
            close();
        }
    };

    const clickScroll = (type: "up" | "down") => {
        if (!groupElement.current) return;
        const y = type === "up" ? 0 : groupElement.current.scrollHeight;
        groupElement.current.scroll(0, y);
    };

    const clickHandle = (ev: React.MouseEvent) => {
        if (ev.target !== groupElement.current) return;

        const selection = window.getSelection();
        if (selection && selection.toString().length !== 0) return;

        close();
    };

    const wheelHandle = (ev: React.WheelEvent) => {
        if (typeof onScroll === "function") {
            onScroll(ev.nativeEvent, groupElement.current as HTMLElement);
        }
    };

    const setScrollMode = (mode: "top" | "bottom" | "none") => {
        setScrollModeTop(mode === "top");
        setScrollModeBottom(mode === "bottom");
    };

    const clearScrollMode = () => setScrollMode("none");

    const onClose = (handler: () => void) => {
        frames.forEach((frame) => frame.onClose(handler));
    };

    // 명령형 API (Frame 클래스가 사용)
    useEffect(() => {
        apiRef.current = {
            get closed() {
                return closedRef.current;
            },
            set closed(v: boolean) {
                setClosed(v);
            },
            get inputFocus() {
                return inputFocus.current;
            },
            get groupElement() {
                return groupElement.current;
            },
            get commentFrameRef() {
                return commentFrameRef.current;
            },
            setScrollMode,
            clearScrollMode,
            close,
            fadeIn,
            onClose
        };
    });

    const className = [
        "refresher-frame-outer",
        background ? "background" : "",
        blur ? "blur" : "",
        fade ? "fadeIn" : "fadeOut",
        fade ? "stack" : ""
    ].filter(Boolean).join(" ");

    return (
        <InputFocusContext.Provider value={inputFocus}>
            <div
                className={className}
                style={{display: closed ? "none" : undefined}}
            >
                <div
                    className="refresher-group"
                    onClick={clickHandle}
                    onWheel={wheelHandle}
                    ref={groupElement}
                >
                    {frames[0] && (
                        <Frame
                            frame={frames[0]}
                            index={0}
                        />
                    )}
                    {frames[1] && (
                        <Frame
                            frame={frames[1]}
                            index={1}
                            registerIncrement={(fn) => {
                                commentFrameRef.current = {incrementCommentKey: fn};
                            }}
                        />
                    )}

                    <div id="scroll">
                        <ChevronUp
                            className="scroll-icon"
                            onClick={() => clickScroll("up")}
                        />
                        <ChevronDown
                            className="scroll-icon"
                            onClick={() => clickScroll("down")}
                        />
                    </div>
                </div>
                {scrollModeTop && <ScrollIndicator side="top"/>}
                {scrollModeBottom && <ScrollIndicator side="bottom"/>}
            </div>
        </InputFocusContext.Provider>
    );
}
