// src/components/scroll.vue
<template>
    <div class="refresher-scroll" :class="{top: side === 'top'}">
        <div class="center">
            <p>한번 더 스크롤 하면 {{ side === 'top' ? '이전' : '다음' }} 게시글을 봅니다.</p>
        </div>
    </div>
</template>

<script>
export default {
    name: "refresher-scroll",
    props: {
        side: {
            type: String,
            required: true
        }
    }
};
</script>

// src/entrypoints/content/modules/preview/components/frame/scroll.tsx
import "./scroll.scss";

interface Props {
    side: "top" | "bottom";
}

export default function ScrollIndicator({side}: Props) {
    return (
        <div className={side === "top" ? "refresher-scroll top" : "refresher-scroll"}>
            <div className="center">
                <p>
                    한번 더 스크롤 하면
                    {side === "top" ? "이전" : "다음"} 게시글을 봅니다.
                </p>
            </div>
        </div>
    );
}
