// src/entrypoints/options/App.vue
<template>
  <div id="refresher-app" class="options-page">
    <BlockDialog
        :block-detect-mode-type-names="blockDetectModeTypeNames"
        :block-key-names="blockKeyNames"
        :current-block-type="currentBlockType"
        :form-data="blockFormData"
        :visible="showBlockDialog"
        @close="closeBlockDialog"
        @confirm="confirmAddBlock"
    />

    <div class="refresher-title-zone">
      <h1>설정</h1>
      <div class="float-right">
        <p
            v-for="tabItem in tabs"
            :key="tabItem.id"
            :class="{ active: tab === tabItem.id }"
            @click="() => (tab = tabItem.id)"
        >
          {{ tabItem.label }}
        </p>
      </div>
    </div>

    <transition-group name="refresher-slide-left">
      <GeneralTab
          v-if="tab === 0"
          key="tab1"
      />
      <BlockTab
          v-else-if="tab === 1"
          key="tab2"
      />
      <MemoTab
          v-else-if="tab === 2"
          key="tab3"
      />
      <ModuleTab
          v-else-if="tab === 3"
          key="tab4"
      />
      <ShortcutTab
          v-else-if="tab === 4"
          key="tab5"
      />
      <DataTab
          v-else-if="tab === 5"
          key="tab6"
      />
    </transition-group>
  </div>
</template>

<script lang="ts" setup>
import {provide, ref} from "vue";

import BlockDialog from "../popup/components/BlockDialog.vue";
import GeneralTab from "../popup/tabs/GeneralTab.vue";
import BlockTab from "../popup/tabs/BlockTab.vue";
import MemoTab from "../popup/tabs/MemoTab.vue";
import ModuleTab from "../popup/tabs/ModuleTab.vue";
import ShortcutTab from "../popup/tabs/ShortcutTab.vue";
import DataTab from "../popup/tabs/DataTab.vue";

import {useBlocks} from "../popup/composables/useBlocks";
import {useMemos} from "../popup/composables/useMemos";
import {useSettings} from "../popup/composables/useSettings";
import {useData} from "../popup/composables/useData";

const tab = ref(0);
const tabs = [
  {id: 0, label: "일반"},
  {id: 1, label: "차단"},
  {id: 2, label: "메모"},
  {id: 3, label: "모듈"},
  {id: 4, label: "단축키"},
  {id: 5, label: "데이터"}
] as const;

const blocksComposable = useBlocks();
const memosComposable = useMemos();
const settingsComposable = useSettings();
const dataComposable = useData();

const {
  blockKeyNames,
  blockDetectModeTypeNames,
  currentBlockType,
  blockFormData,
  showBlockDialog,
  closeBlockDialog,
  confirmAddBlock
} = blocksComposable;

const {moveToModuleTab: moveToModuleTabRaw} = settingsComposable;

const moveToModuleTab = (moduleName: string) => {
  tab.value = 4;
  moveToModuleTabRaw(moduleName);
};

provide("blocks", blocksComposable);
provide("memos", memosComposable);
provide("settings", settingsComposable);
provide("data", dataComposable);
provide("updateUserSetting", settingsComposable.updateUserSetting);
provide("typeWrap", settingsComposable.typeWrap);
provide("moveToModuleTab", moveToModuleTab);
</script>

<style lang="scss" src="../popup/popup.scss"></style>

<style lang="scss">
/* options 페이지 전용 - popup 고정 크기/위치 제거 */
html, body {
  height: auto;
  min-height: 100vh;
  overflow-y: auto;
  margin: 0;
  padding: 0;
}

#refresher-app.options-page {
  width: 100% !important;
  height: auto !important;
  min-height: 100vh;
  max-width: none !important;
  margin: 0 !important;
  border-radius: 0 !important;
  overflow: visible;
  display: block;

  .refresher-title-zone {
    position: relative !important;
    width: 100%;
    max-width: 1200px;
    margin: 0 auto;
    padding: 10px 24px;
    box-sizing: border-box;
    z-index: auto;
  }

  .tab {
    position: relative !important;
    width: 100% !important;
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px 24px 40px;
    height: auto !important;
    box-sizing: border-box;
    overflow-y: visible;
  }
}
</style>

// src/entrypoints/popup/App.tsx
import {ExternalLink} from "lucide-react";
import {useState} from "react";

import BlockDialog from "./components/BlockDialog";
import {AppContext, type AppContextValue} from "./context";
import {useBlocks} from "./hooks/useBlocks";
import {useData} from "./hooks/useData";
import {useMemos} from "./hooks/useMemos";
import {useSettings} from "./hooks/useSettings";
import BlockTab from "./tabs/BlockTab";
import DataTab from "./tabs/DataTab";
import GeneralTab from "./tabs/GeneralTab";
import MemoTab from "./tabs/MemoTab";
import ModuleTab from "./tabs/ModuleTab";
import ShortcutTab from "./tabs/ShortcutTab";

import "./popup.scss";

const tabs = [
    {id: 0, label: "일반"},
    {id: 1, label: "차단"},
    {id: 2, label: "메모"},
    {id: 3, label: "모듈"},
    {id: 4, label: "단축키"},
    {id: 5, label: "데이터"}
] as const;

export default function App({optionsPage}: { optionsPage?: boolean }) {
    const [tab, setTab] = useState(0);

    const blocksComposable = useBlocks();
    const memosComposable = useMemos();
    const settingsComposable = useSettings();
    const dataComposable = useData();

    const moveToModuleTab = (moduleName: string) => {
        setTab(3);
        settingsComposable.moveToModuleTab(moduleName);
    };

    const ctx: AppContextValue = {
        blocks: blocksComposable,
        memos: memosComposable,
        settings: settingsComposable,
        data: dataComposable,
        moveToModuleTab
    };

    const openOptions = () => {
        browser.runtime.openOptionsPage();
    };

    return (
        <AppContext.Provider value={ctx}>
            <div className={optionsPage ? "refresher-app options-page" : "refresher-app"} id="refresher-app">
                <BlockDialog
                    blockDetectModeTypeNames={blocksComposable.blockDetectModeTypeNames}
                    blockKeyNames={blocksComposable.blockKeyNames}
                    currentBlockType={blocksComposable.currentBlockType}
                    formData={blocksComposable.blockFormData}
                    onChange={blocksComposable.updateBlockForm}
                    onClose={blocksComposable.closeBlockDialog}
                    onConfirm={() => void blocksComposable.confirmAddBlock()}
                    visible={blocksComposable.showBlockDialog}
                />

                <div className="refresher-title-zone">
                    <h1>설정</h1>
                    <div className="float-right">
                        {tabs.map((tabItem) => (
                            <p
                                className={tab === tabItem.id ? "active" : undefined}
                                key={tabItem.id}
                                onClick={() => setTab(tabItem.id)}
                            >
                                {tabItem.label}
                            </p>
                        ))}
                    </div>
                    {!optionsPage && (
                        <button
                            className="open-options-btn"
                            onClick={openOptions}
                            title="전체 설정 페이지 열기"
                        >
                            <ExternalLink size={14}/>
                        </button>
                    )}
                </div>

                {tab === 0 && <GeneralTab key="tab1"/>}
                {tab === 1 && <BlockTab key="tab2"/>}
                {tab === 2 && <MemoTab key="tab3"/>}
                {tab === 3 && <ModuleTab key="tab4"/>}
                {tab === 4 && <ShortcutTab key="tab5"/>}
                {tab === 5 && <DataTab key="tab6"/>}
            </div>
        </AppContext.Provider>
    );
}
