// src/views/components/options.vue
<template>
    <select
        v-model="value"
        :data-id="id"
        :data-module="modname"
        :disabled="disabled"
        class="refresher-options"
        @change="update">
        <option v-for="(value, key) in options" :value="key">{{ value }}</option>
    </select>
</template>

<script lang="ts">
import Vue, {PropType} from "vue";

export default Vue.extend({
    name: "refresher-options",
    props: {
        change: {
            type: Function
        },

        modname: {
            type: String
        },

        options: {
            type: Object as PropType<Record<string, string>>
        },

        id: {
            type: String
        },

        value: {
            type: String
        },

        disabled: {
            type: Boolean
        }
    },
    methods: {
        update(ev: any) {
            this.change?.(
                ev.target.dataset.module,
                ev.target.dataset.id,
                ev.target.value
            );
        }
    }
});
</script>

// src/entrypoints/popup/components/options.tsx
import "./options.scss";

interface Props {
    options?: Record<string, string>;
    value?: string;
    disabled?: boolean;
    onChange?: (value: string) => void;
}

export default function Options({options = {}, value = "", disabled = false, onChange}: Props) {
    const handleChange = (ev: React.ChangeEvent<HTMLSelectElement>) => {
        onChange?.(ev.target.value);
    };

    return (
        <select
            className="refresher-options"
            disabled={disabled}
            onChange={handleChange}
            value={value}
        >
            {Object.entries(options).map(([key, optionValue]) => (
                <option key={key} value={key}>
                    {optionValue}
                </option>
            ))}
        </select>
    );
}
