// src/views/components/range.vue
<template>
    <div class="refresher-range">
        <input type="range" :data-id="id" :data-module="modname" :placeholder="placeholder" :value="value"
               :disabled="disabled" v-on:input="input" v-on:change="update" :max="max" :min="min" :step="step"></input>
        <span class="indicator">{{ value + (this.unit ? this.unit : '') }}</span>
    </div>
</template>

<script>
export default {
    name: "refresher-range",
    props: {
        change: {
            type: Function
        },

        placeholder: {
            type: Number,
            required: false
        },

        modname: {
            type: String
        },

        id: {
            type: String
        },

        value: {
            type: Number
        },

        max: {
            type: Number
        },

        min: {
            type: Number
        },

        step: {
            type: Number
        },

        unit: {
            type: String
        },

        disabled: {
            type: Boolean
        }
    },
    methods: {
        input(ev) {
            this.$el.querySelector(".indicator").innerHTML =
                ev.target.value + (this.unit ? this.unit : "");
        },

        update(ev) {
            if (this.change) {
                this.change(
                    ev.target.dataset.module,
                    ev.target.dataset.id,
                    ev.target.value
                );
            }
        }
    },
    mounted() {
        this.$data.__temp = this.value;
    }
};
</script>

// src/entrypoints/popup/components/range.tsx
import {useEffect, useState} from "react";

import "./range.scss";

interface Props {
    value?: number;
    placeholder?: string;
    max?: number;
    min?: number;
    step?: number;
    unit?: string;
    disabled?: boolean;
    onChange?: (value: number) => void;
}

export default function Range({
    value = 0,
    placeholder,
    max = 100,
    min = 0,
    step = 1,
    unit = "",
    disabled = false,
    onChange
}: Props) {
    const [currentValue, setCurrentValue] = useState(value);

    useEffect(() => {
        setCurrentValue(value);
    }, [value]);

    const handleChange = (ev: React.ChangeEvent<HTMLInputElement>) => {
        const next = Number(ev.target.value);
        setCurrentValue(next);
        onChange?.(next);
    };

    return (
        <div className="refresher-range">
            <input
                disabled={disabled}
                max={max}
                min={min}
                onChange={handleChange}
                placeholder={placeholder}
                step={step}
                type="range"
                value={currentValue}
            />
            <span className="indicator">{`${currentValue}${unit}`}</span>
        </div>
    );
}
