// src/entrypoints/popup/components/settingItem.vue
<template>
  <div
      :data-changed="setting.value !== setting.default"
      class="refresher-setting"
  >
    <div class="info">
      <h4>{{ setting.name }}</h4>
      <p>{{ setting.desc }}</p>
      <p class="mute">(기본 값 : {{ typeWrap(setting.default) }})</p>
    </div>

    <setting-control
        :module-enabled="moduleEnabled"
        :module-name="moduleName"
        :setting="setting"
        :setting-key="settingKey"
    />
  </div>
</template>

<script lang="ts" setup>
import {inject} from "vue";
import SettingControl from "./settingControl.vue";

interface Props {
  setting: RefresherSettings;
  settingKey: string;
  moduleName: string;
  moduleEnabled: boolean;
}

defineProps<Props>();

const typeWrap = inject<(value: unknown) => string | unknown>("typeWrap")!;
</script>

// src/entrypoints/popup/components/settingItem.tsx
import SettingControl from "./settingControl";
import {useAppContext} from "../context";

interface Props {
    setting: RefresherSettings;
    settingKey: string;
    moduleName: string;
    moduleEnabled: boolean;
}

export default function SettingItem({setting, settingKey, moduleName, moduleEnabled}: Props) {
    const {settings} = useAppContext();

    return (
        <div
            className="refresher-setting"
            data-changed={setting.value !== setting.default}
        >
            <div className="info">
                <h4>{setting.name}</h4>
                <p>{setting.desc}</p>
                <p className="mute">(기본 값 : {String(settings.typeWrap(setting.default))})</p>
            </div>

            <SettingControl
                moduleEnabled={moduleEnabled}
                moduleName={moduleName}
                setting={setting}
                settingKey={settingKey}
            />
        </div>
    );
}
