// src/entrypoints/popup/components/settingControl.tsx
import Checkbox from "./checkbox";
import Options from "./options";
import Range from "./range";
import RefresherInput from "./refresherInput";
import {useAppContext} from "../context";

interface Props {
    setting: RefresherSettings;
    settingKey: string;
    moduleName: string;
    moduleEnabled: boolean;
}

export default function SettingControl({setting, settingKey, moduleName, moduleEnabled}: Props) {
    const {settings} = useAppContext();

    const onChange = (value: unknown) => {
        void settings.updateUserSetting(moduleName, settingKey, value);
    };

    return (
        <div className="control">
            {setting.type === "check" && (
                <Checkbox
                    disabled={!moduleEnabled}
                    onChange={onChange}
                    value={Boolean(setting.value)}
                />
            )}
            {setting.type === "text" && (
                <RefresherInput
                    disabled={!moduleEnabled}
                    onChange={onChange}
                    placeholder={setting.default as string | undefined}
                    value={String(setting.value ?? "")}
                />
            )}
            {setting.type === "range" && (
                <Range
                    disabled={!moduleEnabled}
                    max={setting.max}
                    min={setting.min}
                    onChange={onChange}
                    placeholder={String(setting.default)}
                    step={setting.step}
                    unit={setting.unit}
                    value={Number(setting.value)}
                />
            )}
            {setting.type === "option" && (
                <Options
                    disabled={!moduleEnabled}
                    onChange={onChange}
                    options={setting.items as Record<string, string>}
                    value={String(setting.value ?? "")}
                />
            )}
        </div>
    );
}

// src/entrypoints/popup/components/settingControl.vue
<template>
    <div class="control">
        <refresher-checkbox
            v-if="setting.type === 'check'"
            v-model="setting.value"
            :disabled="!moduleEnabled"
            @change="onChange"
        />
        <refresher-input
            v-else-if="setting.type === 'text'"
            :disabled="!moduleEnabled"
            :placeholder="setting.default"
            :value="setting.value"
            @change="onChange"
        />
        <refresher-range
            v-else-if="setting.type === 'range'"
            :disabled="!moduleEnabled"
            :max="setting.max"
            :min="setting.min"
            :model-value="Number(setting.value)"
            :placeholder="String(setting.default)"
            :step="setting.step"
            :unit="setting.unit"
            @change="onChange"
        />
        <refresher-options
            v-else-if="setting.type === 'option'"
            :disabled="!moduleEnabled"
            :options="setting.items as Record<string, string>"
            :value="setting.value"
            @change="onChange"
        />
    </div>
</template>

<script lang="ts" setup>
import {inject} from "vue";
import RefresherCheckbox from "./checkbox.vue";
import RefresherOptions from "./options.vue";
import RefresherRange from "./range.vue";
import RefresherInput from "./refresherInput.vue";

interface Props {
    setting: RefresherSettings;
    settingKey: string;
    moduleName: string;
    moduleEnabled: boolean;
}

const props = defineProps<Props>();

const updateUserSetting = inject<(module: string, key: string, value: unknown) => void>("updateUserSetting")!;

const onChange = (value: unknown) => {
    updateUserSetting(props.moduleName, props.settingKey, value);
};
</script>
