// src/popup/components/settingControl.vue
<template>
    <div class="control">
        <refresher-checkbox
            v-if="setting.type === 'check'"
            :id="settingKey"
            :change="updateUserSetting"
            :checked="setting.value"
            :disabled="!moduleEnabled"
            :modname="moduleName"
        />
        <refresher-input
            v-else-if="setting.type === 'text'"
            :id="settingKey"
            :change="updateUserSetting"
            :disabled="!moduleEnabled"
            :modname="moduleName"
            :placeholder="setting.default"
            :value="setting.value"
        />
        <refresher-range
            v-else-if="setting.type === 'range'"
            :id="settingKey"
            :change="updateUserSetting"
            :disabled="!moduleEnabled"
            :max="setting.max"
            :min="setting.min"
            :modname="moduleName"
            :placeholder="setting.default"
            :step="setting.step"
            :unit="setting.unit"
            :value="Number(setting.value)"
        />
        <refresher-options
            v-else-if="setting.type === 'option'"
            :id="settingKey"
            :change="updateUserSetting"
            :disabled="!moduleEnabled"
            :modname="moduleName"
            :options="setting.items"
            :value="setting.value"
        />
    </div>
</template>

<script lang="ts" setup>
import RefresherCheckbox from './checkbox.vue';
import RefresherInput from './refresherInput.vue';
import RefresherRange from './range.vue';
import RefresherOptions from './options.vue';

interface Props {
    setting: RefresherSettings;
    settingKey: string;
    moduleName: string;
    moduleEnabled: boolean;
    updateUserSetting: (module: string, key: string, value: unknown) => void;
}

defineProps<Props>();
</script>

// src/entrypoints/popup/components/settingControl.tsx
import Checkbox from "./checkbox";
import Options from "./options";
import Range from "./range";
import RefresherInput from "./refresherInput";
import {useAppContext} from "../context";

interface Props {
    setting: RefresherSettings;
    settingKey: string;
    moduleName: string;
    moduleEnabled: boolean;
}

export default function SettingControl({setting, settingKey, moduleName, moduleEnabled}: Props) {
    const {settings} = useAppContext();

    const onChange = (value: unknown) => {
        void settings.updateUserSetting(moduleName, settingKey, value);
    };

    return (
        <div className="control">
            {setting.type === "check" && (
                <Checkbox
                    disabled={!moduleEnabled}
                    onChange={onChange}
                    value={Boolean(setting.value)}
                />
            )}
            {setting.type === "text" && (
                <RefresherInput
                    disabled={!moduleEnabled}
                    onChange={onChange}
                    placeholder={setting.default as string | undefined}
                    value={String(setting.value ?? "")}
                />
            )}
            {setting.type === "range" && (
                <Range
                    disabled={!moduleEnabled}
                    max={setting.max}
                    min={setting.min}
                    onChange={onChange}
                    placeholder={String(setting.default)}
                    step={setting.step}
                    unit={setting.unit}
                    value={Number(setting.value)}
                />
            )}
            {setting.type === "option" && (
                <Options
                    disabled={!moduleEnabled}
                    onChange={onChange}
                    options={setting.items as Record<string, string>}
                    value={String(setting.value ?? "")}
                />
            )}
        </div>
    );
}
