// src/entrypoints/popup/tabs/MemoTab.vue
<template>
  <div class="tab tab3">
    <div class="section-header">
      <h2>데이터 관리</h2>
      <div class="section-actions">
        <button @click="exportMemo">내보내기</button>
        <button @click="importMemo">가져오기</button>
        <button @click="open('https://dcrefresher.green1052.com/utils/convert-memo')">메모 변환</button>
      </div>
      <br/>
    </div>

    <div
        v-for="key in memoTypes"
        :key="key"
        class="block-divide"
    >
      <h3>
        {{ memoKeyNames[key] }} ({{ Object.keys(memos[key]).length }}개)
        <span
            class="plus"
            @click="addMemoUser(key)"
        >
          <PlusIcon/>
        </span>
        <span
            class="remove"
            @click="removeAllMemoUser(key)"
        >
          <RemoveIcon/>
        </span>
      </h3>

      <div class="lists">
        <p v-if="!Object.keys(memos[key]).length">{{ memoKeyNames[key] }} 메모 없음</p>
        <refresher-bubble
            v-for="[user, memo] in Object.entries(memos[key])"
            v-else
            :key="`memo:${user}`"
            :remove="() => removeMemoUser(key, user)"
            :text="`${user} (${memo.text.substring(0, 10)})`"
            :textclick="() => editMemoUser(key, user)"
        />
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import {inject} from "vue";
import RefresherBubble from "../components/bubble.vue";
import {PlusIcon, RemoveIcon} from "../components/icons";

const {
  memos,
  memoKeyNames,
  memoTypes,
  removeMemoUser,
  removeAllMemoUser,
  addMemoUser,
  editMemoUser,
  exportMemo,
  importMemo
} = inject("memos")!;

const open = (url: string) => {
  browser.tabs.create({url});
};
</script>

// src/entrypoints/popup/tabs/MemoTab.tsx
import Bubble from "../components/bubble";
import {PlusIcon, RemoveIcon} from "../components/icons";
import {useAppContext} from "../context";

export default function MemoTab() {
    const {memos} = useAppContext();
    const {
        memos: memoLists,
        memoKeyNames,
        memoTypes,
        removeMemoUser,
        removeAllMemoUser,
        addMemoUser,
        editMemoUser,
        exportMemo,
        importMemo
    } = memos;

    const open = (url: string) => {
        browser.tabs.create({url});
    };

    return (
        <div className="tab tab3">
            <div className="section-header">
                <h2>데이터 관리</h2>
                <div className="section-actions">
                    <button onClick={() => void exportMemo()}>내보내기</button>
                    <button onClick={() => void importMemo()}>가져오기</button>
                    <button onClick={() => open("https://dcrefresher.green1052.com/utils/convert-memo")}>메모 변환</button>
                </div>
                <br/>
            </div>

            {memoTypes.map((key) => (
                <div
                    className="block-divide"
                    key={key}
                >
                    <h3>
                        {memoKeyNames[key]} ({Object.keys(memoLists[key]).length}개)
                        <span
                            className="plus"
                            onClick={() => void addMemoUser(key)}
                        >
                            <PlusIcon/>
                        </span>
                        <span
                            className="remove"
                            onClick={() => void removeAllMemoUser(key)}
                        >
                            <RemoveIcon/>
                        </span>
                    </h3>

                    <div className="lists">
                        {Object.keys(memoLists[key]).length === 0 && <p>{memoKeyNames[key]} 메모 없음</p>}
                        {Object.entries(memoLists[key]).map(([user, memo]) => (
                            <Bubble
                                key={`memo:${user}`}
                                remove={() => void removeMemoUser(key, user)}
                                text={`${user} (${memo.text.substring(0, 10)})`}
                                textclick={() => void editMemoUser(key, user)}
                            />
                        ))}
                    </div>
                </div>
            ))}
        </div>
    );
}
