// src/entrypoints/popup/tabs/ModuleTab.vue
<template>
    <div class="tab tab4">
        <div
            v-if="!hasModules"
            class="refresher-no-modules"
        >
            <h3>로드된 모듈 없음</h3>
            <p>우선 디시 페이지를 열어주세요.</p>
        </div>
        <div v-else>
            <refresher-module
                v-for="module in modules"
                :key="module.name"
                :desc="module.description ?? ''"
                :enabled="module.enable"
                :name="module.name"
            />
        </div>
    </div>
</template>

<script lang="ts" setup>
import {inject} from "vue";
import RefresherModule from "../components/module.vue";

const {modules, hasModules} = inject("settings")!;
</script>

// src/entrypoints/popup/tabs/ModuleTab.tsx
import ModuleCard from "../components/module";
import {useAppContext} from "../context";

export default function ModuleTab() {
    const {settings} = useAppContext();
    const {modules, hasModules} = settings;

    return (
        <div className="tab tab4">
            {!hasModules ? (
                <div className="refresher-no-modules">
                    <h3>로드된 모듈 없음</h3>
                    <p>우선 디시 페이지를 열어주세요.</p>
                </div>
            ) : (
                <div>
                    {Object.values(modules).map((module) => (
                        <ModuleCard
                            desc={module.description ?? ""}
                            enabled={module.enable}
                            key={module.name}
                            name={module.name}
                        />
                    ))}
                </div>
            )}
        </div>
    );
}
