// src/entrypoints/popup/tabs/ShortcutTab.tsx
import type {Browser} from "#imports";
import {useEffect, useState} from "react";

import Bubble from "../components/bubble";

export default function ShortcutTab() {
    const [shortcuts, setShortcuts] = useState<Browser.commands.Command[]>([]);

    const openShortcutSettings = () => {
        browser.tabs.create({
            url: (import.meta.env.FIREFOX as boolean) ? "about:addons" : "chrome://extensions/shortcuts"
        });
    };

    useEffect(() => {
        void browser.commands.getAll().then(setShortcuts);
    }, []);

    return (
        <div className="tab tab5">
            <div className="shortcut-lists">
                {shortcuts.map((shortcut) =>
                    shortcut.description?.length ? (
                        <div
                            className="refresher-shortcut"
                            key={shortcut.name}
                        >
                            <p className="description">{shortcut.description}</p>
                            <div className="key">
                                <Bubble text={shortcut.shortcut || "없음"}/>
                            </div>
                        </div>
                    ) : null
                )}
            </div>
            <p className="shortcut-settings-link"><a onClick={openShortcutSettings}>단축키 설정</a></p>
        </div>
    );
}

// src/entrypoints/popup/tabs/ShortcutTab.vue
<template>
    <div class="tab tab5">
        <div class="shortcut-lists">
            <template
                v-for="shortcut in shortcuts"
                :key="shortcut.name"
            >
                <div
                    v-if="shortcut.description?.length"
                    class="refresher-shortcut"
                >
                    <p class="description">{{ shortcut.description }}</p>
                    <div class="key">
                        <refresher-bubble :text="shortcut.shortcut || '없음'"/>
                    </div>
                </div>
            </template>
        </div>
        <p class="shortcut-settings-link"><a @click="openShortcutSettings">단축키 설정</a></p>
    </div>
</template>

<script lang="ts" setup>
import type {Browser} from "#imports";
import {onMounted, ref} from "vue";
import RefresherBubble from "../components/bubble.vue";

const shortcuts = ref<Browser.commands.Command[]>([]);

const openShortcutSettings = () => {
    browser.tabs.create({
        url: (import.meta.env.FIREFOX as boolean) ? "about:addons" : "chrome://extensions/shortcuts"
    });
};

onMounted(async () => {
    shortcuts.value = await browser.commands.getAll();
});
</script>
