// src/views/components/checkbox.vue
<template>
    <div :class="{disabled: disabled}" :data-id="id" :data-module="modname" :data-on="on" class="refresher-checkbox"
         v-on:click="toggle">
        <div :style="{transform: 'translateX(' + (typeof translateX !== 'undefined' ? translateX : (this.on ? 18 : 0)) + 'px)'}"
             class="selected"
             v-on:pointerdown="down" v-on:pointermove="hover" v-on:pointerout="out" v-on:pointerup="up">
        </div>
    </div>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
    name: "refresher-checkbox",

    props: {
        change: {
            type: Function
        },

        modname: {
            type: String,
            required: false
        },

        id: {
            type: String
        },

        checked: {
            type: Boolean
        },

        disabled: {
            type: Boolean
        }
    },

    data() {
        return {
            on: this.checked,
            _down: false,
            translateX: undefined,
            onceOut: false
        };
    },

    methods: {
        toggle() {
            if (this.disabled) {
                return;
            }

            if (this.onceOut) {
                this.onceOut = false;

                return;
            }

            this.on = !this.on;

            this.change && this.change(this.$el.dataset.module, this.$el.dataset.id, this.on);
        },

        hover(ev: PointerEvent) {
            if (this.disabled) {
                return;
            }

            if (this._down) {
                this.translateX = Math.ceil(ev.offsetX);
            }
        },

        down() {
            if (this.disabled) {
                return;
            }

            this._down = true;
        },

        up() {
            if (this.disabled) {
                return;
            }

            this._down = false;
            this.translateX = undefined;
        },
        out() {
            if (this.disabled) {
                return;
            }

            if (this._down) {
                this._down = false;
                this.translateX = undefined;
                this.toggle();

                this.onceOut = true;
            }
        }
    }
});
</script>

// src/views/Checkbox.tsx
import React, {PointerEvent, useCallback, useState} from "react";

export function Checkbox({onChange, module, id, checked, disabled}: {
    onChange: (module: string, key: string, value: unknown) => void;
    module: string;
    id: string;
    checked: boolean;
    disabled: boolean;
}) {
    const [on, setOn] = useState(checked);
    const [down, setDown] = useState(false);
    const [translateX, setTranslateX] = useState<number | null>(null);
    const [onceOut, setOnceOut] = useState(false);

    const onToggle = useCallback(() => {
        if (disabled) return;

        if (onceOut) {
            setOnceOut(false);
            return;
        }

        onChange(module, id, !on);
        setOn(!on);
    }, [on, onceOut]);

    const onDown = useCallback(() => {
        if (disabled) return;
        setDown(true);
    }, [down]);

    const onHover = useCallback((ev: PointerEvent<HTMLDivElement>) => {
        if (disabled || !down) return;
        setTranslateX(Math.ceil(ev.nativeEvent.offsetX));
    }, [down, translateX]);

    const onOut = useCallback(() => {
        if (disabled || !down) return;

        setDown(false);
        setTranslateX(null);
        setOnceOut(true);
        onToggle();
    }, [down, translateX, onceOut]);

    const onUp = useCallback(() => {
        if (disabled) return;
        setDown(false);
        setTranslateX(null);
    }, [down, translateX]);

    return (
        <div
            className={`refresher-checkbox ${disabled ? "disabled" : ""}`}
            onClick={onToggle}
            data-on={on}
        >
            <div
                className="selected"
                style={{transform: `translateX(${translateX ?? on ? 18 : 0}px)`}}
                onPointerDown={onDown}
                onPointerMove={onHover}
                onPointerOut={onOut}
                onPointerUp={onUp}
            />
        </div>
    );
}
