// src/views/components/module.vue
<template>
    <div class="refresher-module">
        <div class="left">
            <p class="title">
                {{ name }}
            </p>
            <p class="desc">
                {{ desc }}
            </p>
            <p class="mute">요구 유틸 : {{ requirement?.join(", ") || "없음" }}</p>
        </div>
        <div class="right">
            <refresher-checkbox
                :change="update"
                :checked="enabled"
            />
        </div>
    </div>
</template>

<script lang="ts">
import Vue from "vue";
import browser from "webextension-polyfill";

import storage from "../../utils/storage";
import checkbox from "./checkbox.vue";

export default Vue.extend({
    name: "RefresherModule",
    components: {
        "refresher-checkbox": checkbox
    },
    props: {
        name: {
            type: String,
            required: true
        },
        desc: {
            type: String,
            required: true
        },
        requirement: {
            type: Array
        },
        enabled: {
            type: Boolean,
            required: true
        }
    },
    methods: {
        async update(module: RefresherModule, id: string, value: boolean) {
            await storage.set(`${this.name}.enable`, value);

            const tabs = await browser.tabs.query({ active: true });

            for (const tab of tabs) {
                browser.tabs.sendMessage(tab.id!, {
                    type: "updateModuleStatus",
                    data: {
                        name: this.name,
                        value
                    }
                });
            }
        }
    }
});
</script>

// src/views/Module.tsx
import React from "react";
import {Checkbox} from "./Checkbox";

export function Module({name, desc, requirement, enabled}: {
    name: string;
    desc: string;
    requirement: string[];
    enabled: boolean;
}) {
    const onChange = (module: string, key: string, value: unknown) => {

    };
    
    return (
        <div className="refresher-module">
            <div className="left">
                <p className="title">{name}</p>
                <p className="desc">{desc}</p>
                <p className="mute">
                    요구 유틸 : {requirement ? requirement.join(", ") : "없음"}
                </p>
            </div>

            <div className="right">
                <Checkbox onChange={onChange} module={name} id={name} checked={enabled} disabled={false}/>
            </div>
        </div>
    );
}
