// src/views/components/options.vue
<template>
    <select
        v-model="value"
        :data-id="id"
        :data-module="modname"
        :disabled="disabled"
        class="refresher-options"
        @change="update">
        <option v-for="(value, key) in options" :value="key">{{ value }}</option>
    </select>
</template>

<script lang="ts">
import Vue, {PropType} from "vue";

export default Vue.extend({
    name: "refresher-options",
    props: {
        change: {
            type: Function
        },

        modname: {
            type: String
        },

        options: {
            type: Object as PropType<Record<string, string>>
        },

        id: {
            type: String
        },

        value: {
            type: String
        },

        disabled: {
            type: Boolean
        }
    },
    methods: {
        update(ev: any) {
            this.change?.(
                ev.target.dataset.module,
                ev.target.dataset.id,
                ev.target.value
            );
        }
    }
});
</script>

// src/views/Options.tsx
import React, {ChangeEvent, useCallback, useState} from "react";

export function Options({onChange, module, id, options, value, disabled}: {
    onChange: (module: string, key: string, value: unknown) => void;
    module: string;
    id: string;
    options: Record<string, string>
    value: string;
    disabled: boolean;
}) {
    const [selectedItem, setSelectedItem] = useState(value);

    const onInput = useCallback((ev: ChangeEvent<HTMLSelectElement>) => {
        setSelectedItem(ev.target.value);
        onChange(module, id, ev.target.value);
    }, [selectedItem]);

    return (
        <select
            className="refresher-options"
            disabled={disabled}
            onChange={onInput}
            defaultValue={selectedItem}
        >
            {Object.entries(options).map(([value2, key]) => (
                <option value={value2}>
                    {key}
                </option>
            ))}
        </select>
    );
}
