// src/views/components/range.vue
<template>
    <div class="refresher-range">
        <input type="range" :data-id="id" :data-module="modname" :placeholder="placeholder" :value="value"
               :disabled="disabled" v-on:input="input" v-on:change="update" :max="max" :min="min" :step="step"></input>
        <span class="indicator">{{ value + (this.unit ? this.unit : '') }}</span>
    </div>
</template>

<script>
export default {
    name: "refresher-range",
    props: {
        change: {
            type: Function
        },

        placeholder: {
            type: Number,
            required: false
        },

        modname: {
            type: String
        },

        id: {
            type: String
        },

        value: {
            type: Number
        },

        max: {
            type: Number
        },

        min: {
            type: Number
        },

        step: {
            type: Number
        },

        unit: {
            type: String
        },

        disabled: {
            type: Boolean
        }
    },
    methods: {
        input(ev) {
            this.$el.querySelector(".indicator").innerHTML =
                ev.target.value + (this.unit ? this.unit : "");
        },

        update(ev) {
            if (this.change) {
                this.change(
                    ev.target.dataset.module,
                    ev.target.dataset.id,
                    ev.target.value
                );
            }
        }
    },
    mounted() {
        this.$data.__temp = this.value;
    }
};
</script>

// src/views/Range.tsx
import React, {ChangeEvent, useCallback, useState} from "react";

export function Range({onChange, module, id, placeholder, value, max, min, step, unit, disabled}: {
    onChange: (module: string, key: string, value: unknown) => void;
    module: string;
    id: string;
    placeholder: string;
    value: number;
    max: number;
    min: number;
    step: number;
    unit: string;
    disabled: boolean;
}) {
    const [rangeValue, setRangeValue] = useState(value);

    const onUpdate = useCallback((ev: ChangeEvent<HTMLInputElement>) => {
        setRangeValue(Number(ev.target.value));
        onChange(module, id, Number(ev.target.value));
    }, [rangeValue]);

    return (
        <div className="refresher-range">
            <input
                type="range"
                max={max}
                min={min}
                placeholder={placeholder}
                step={step}
                disabled={disabled}
                value={rangeValue}
                onChange={onUpdate}
            />
            <span className="indicator">{rangeValue}{unit}</span>
        </div>
    );
}
