// src/entrypoints/content/modules/preview/components/frame/frame.tsx
import {useEffect, useRef, useState, useSyncExternalStore} from "react";

import Loader from "@/components/loader";
import PreviewButton from "@/components/previewButton";
import Timestamp from "@/components/timestamp";
import UserComponent from "@/components/user";
import {closeDcconPopup, renderDcconPopup} from "@/entrypoints/content/composables/useDcconPopup";

import Comment from "../comment/comment";
import WriteComment from "../comment/write_comment";
import FrameError from "./frameError";
import FrameVotes from "./frameVotes";

import type {PreviewFrame} from "../../frame";

import "./frame.scss";

interface Props {
    frame: PreviewFrame;
    index: number;
    registerIncrement?: (fn: () => void) => void;
}

export default function Frame({frame, index, registerIncrement}: Props) {
    useSyncExternalStore(frame.subscribe, frame.getSnapshot);

    const [reply, setReply] = useState<{ commentNo: string | null; replyNo: string | null }>({
        commentNo: null,
        replyNo: null
    });
    const [commentKey, setCommentKey] = useState(0);
    const [collapsedParents, setCollapsedParents] = useState<Set<string>>(new Set());

    const [dccon, setDccon] = useState<DcinsideDccon[]>([]);
    const [bigDccon, setBigDccon] = useState(false);
    const dcconRef = useRef(dccon);
    dcconRef.current = dccon;
    const bigDcconRef = useRef(bigDccon);
    bigDcconRef.current = bigDccon;

    const data = frame.data;

    const showLoader =
        !!data.comments &&
        (!data.comments.comments || data.comments.comments.length === 0) &&
        !!data.load;

    const mediaBlockClass =
        data.useImageBlock && data.type === "icon_txt"
            ? "refresher-preview-block-media"
            : "";

    const hasComments = !!data.comments?.comments && data.comments.comments.length > 0;

    const allComments: DcinsideCommentObject[] = data.comments?.comments ?? [];

    // 부모 no -> 마지막 답글 no 맵 (선 끝 처리용)
    const lastReplyByParent: Record<string, string> = {};
    for (const c of allComments) {
        if (c.depth === 1 && c.c_no) {
            lastReplyByParent[c.c_no] = c.no;
        }
    }

    const replyCount = (comment: DcinsideCommentObject): number =>
        comment.depth === 0
            ? allComments.filter((c) => c.depth === 1 && c.c_no === comment.no).length
            : 0;

    const isCollapsed = (comment: DcinsideCommentObject): boolean =>
        comment.depth === 0 && collapsedParents.has(comment.no);

    const isLastReply = (comment: DcinsideCommentObject): boolean =>
        comment.depth === 1 && !!comment.c_no && lastReplyByParent[comment.c_no] === comment.no;

    const toggleCollapse = (no: string) => {
        setCollapsedParents((prev) => {
            const next = new Set(prev);
            if (next.has(no)) next.delete(no);
            else next.add(no);
            return next;
        });
    };

    const visibleComments: DcinsideCommentObject[] = collapsedParents.size === 0
        ? allComments
        : allComments.filter((c) =>
            c.depth === 0 || !collapsedParents.has(c.c_no as string)
        );

    const showVotes = data.comments === undefined && data.buttons;

    const upvote = () => frame.functions.vote(1);
    const downvote = () => frame.functions.vote(0);
    const share = () => frame.functions.share();

    const openOriginal = async (): Promise<boolean> => {
        void frame.functions.openOriginal();
        return true;
    };

    // 댓글 새로고침 (retry 래핑)
    const retry = (): Promise<boolean> => {
        void frame.functions.retry(false);
        return Promise.resolve(true);
    };

    // 댓글 작성 영역으로 포커스 이동
    const toCommentWrite = (): Promise<boolean> => {
        document.querySelector<HTMLElement>("#comment_main")?.focus();
        return Promise.resolve(true);
    };

    // 접힌 상태 펼치기
    const expandCollapse = () => {
        frame.collapse = false;
        void frame.functions.load();
    };

    // 댓글 작성 후 새로고침
    const writeComment = async (
        type: "text" | "dccon",
        memo: string | DcinsideDccon[],
        commentNo: string | null,
        replyNo: string | null,
        user: { name: string; pw?: string },
        selectedBigDccon: boolean
    ): Promise<boolean> => {
        try {
            // 실패(false)를 그대로 돌려줘야 write_comment가 입력 내용을 비우지 않는다
            const ok = await frame.functions.writeComment(type, memo, commentNo, replyNo, user, selectedBigDccon);
            if (ok) void retry();
            return ok;
        } catch {
            return false;
        }
    };

    // 프레임 닫힘 시 상태 초기화
    const resetFrameState = () => {
        frame.reset();
        setReply({commentNo: null, replyNo: null});
        setDccon([]);
        setBigDccon(false);
        closeDcconPopup();
        setCommentKey(0);
        setCollapsedParents(new Set());
    };

    const incrementCommentKey = () => {
        setCommentKey((k) => k + 1);
        setCollapsedParents(new Set());
    };

    useEffect(() => {
        frame.onClose(resetFrameState);
        registerIncrement?.(incrementCommentKey);
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    const frameClassName = [
        "refresher-frame",
        frame.options.relative ? "relative" : "",
        frame.options.blur ? "blur" : "",
        frame.options.preview ? "preview" : "",
        frame.options.center ? "center" : ""
    ].filter(Boolean).join(" ");

    return (
        <div className={frameClassName}>
            {frame.error ? (
                <FrameError
                    error={frame.error}
                    retry={retry}
                />
            ) : (
                <div>
                    <div className="refresher-preview-info">
                        <div className="refresher-preview-title-zone">
                            <div className={data.buttons ? "refresher-preview-title-text refresher-title-post" : "refresher-preview-title-text"}>
                                <div
                                    className="refresher-preview-title"
                                    data-index={index + 1}
                                    dangerouslySetInnerHTML={{__html: frame.title}}
                                    key={frame.title}
                                />
                                <span className="refresher-preview-title-mute">{frame.subtitle}</span>
                            </div>

                            {data.comments && (
                                <div className="refresher-comment-controls-container">
                                    {data.useWriteComment && (
                                        <PreviewButton
                                            click={toCommentWrite}
                                            className="refresher-comment-controls"
                                            id="write"
                                        />
                                    )}
                                    <PreviewButton
                                        click={retry}
                                        className="refresher-comment-controls"
                                        id="refresh"
                                    />
                                </div>
                            )}
                        </div>

                        <div className="refresher-preview-meta">
                            {data.user && <UserComponent user={data.user}/>}
                            <div className="float-right">
                                <div className="date-views">
                                    {data.date && <Timestamp date={data.date}/>}
                                    <span className="refresher-views">{data.views}</span>
                                </div>
                                {data.expire && (
                                    <Timestamp
                                        date={data.expire}
                                        mode="remaining"
                                    />
                                )}
                            </div>
                        </div>
                    </div>

                    {frame.collapse ? (
                        <div className="refresher-preview-contents">
                            <div className="refresher-collapse-text">
                                <h3 onClick={expandCollapse}>
                                    댓글 보기를 클릭하여 댓글만 표시합니다. 여기를 눌러 글을 볼 수 있습니다.
                                </h3>
                            </div>
                        </div>
                    ) : (
                        <div className="refresher-preview-contents">
                            {showLoader && <Loader/>}

                            {!data.comments ? (
                                <div
                                    className={`refresher-preview-contents-actual ${mediaBlockClass}`.trim()}
                                    dangerouslySetInnerHTML={{__html: frame.contents ?? ""}}
                                />
                            ) : (
                                <div>
                                    {!hasComments ? (
                                        <div>
                                            <div className="refresher-nocomment-wrap">
                                                <h3>댓글이 없습니다.</h3>
                                            </div>
                                        </div>
                                    ) : (
                                        <div
                                            className="refresher-preview-comments"
                                            key={commentKey}
                                        >
                                            {visibleComments.map((c, i) => (
                                                <Comment
                                                    collapsed={isCollapsed(c)}
                                                    comment={c}
                                                    delete={frame.functions.deleteComment}
                                                    index={i + 1}
                                                    key={c.no}
                                                    lastReply={c.depth === 1 && isLastReply(c)}
                                                    onUpdateReply={setReply}
                                                    onToggleCollapse={toggleCollapse}
                                                    postUser={data.postUserId}
                                                    reply={reply}
                                                    replyCount={replyCount(c)}
                                                    useWriteComment={data.useWriteComment}
                                                />
                                            ))}
                                        </div>
                                    )}

                                    {data.useWriteComment && (
                                        <WriteComment
                                            func={writeComment}
                                            getBigDccon={() => bigDcconRef.current}
                                            getDccon={() => dcconRef.current}
                                            onSetBigDccon={setBigDccon}
                                            onSetDccon={setDccon}
                                            onUpdateReply={setReply}
                                            renderDcconPopup={() =>
                                                renderDcconPopup((selected, big) => {
                                                    setDccon(selected);
                                                    setBigDccon(big);
                                                })
                                            }
                                            reply={reply}
                                        />
                                    )}
                                </div>
                            )}
                        </div>
                    )}

                    {showVotes && (
                        <FrameVotes
                            disabledDownvote={data.disabledDownvote}
                            downvote={downvote}
                            downvotes={frame.downvotes}
                            fixedUpvotes={frame.fixedUpvotes}
                            original={openOriginal}
                            share={share}
                            upvote={upvote}
                            upvotes={frame.upvotes}
                        />
                    )}
                </div>
            )}
        </div>
    );
}

// src/components/frame.vue
<template>
    <div
        :class="{
            relative: frame.options.relative,
            blur: frame.options.blur,
            preview: frame.options.preview,
            center: frame.options.center
        }"
        class="refresher-frame"
    >
        <div
            v-if="frame.error"
            class="refresher-preview-contents refresher-error"
        >
            <h3>{{ frame.error.title || "알 수 없는 오류" }}</h3>
            <br/>
            <br/>
            <br/>
            <p>가능한 경우:</p>

            <ul v-if="!frame.error.detail">
                <li>알 수 없는 오류가 발생했습니다.</li>
            </ul>
            <ul v-else-if="frame.error.detail.includes('Failed to fetch')">
                <li>연결 오류, 서버 오류일 가능성도 있습니다.</li>
                <li>브라우저 오류, 대부분 구현 오류로 확장 프로그램 업데이트가 필요합니다.</li>
                <li>서버 구조 변경으로 인한 잘못된 방식으로 요청. 지속될 경우 개발자에게 문의하세요.</li>
            </ul>
            <ul v-else-if="frame.error.detail.includes('40')">
                <li>게시글이 이미 삭제됨</li>
                <li>게시글이 없음</li>
                <li>서버 구조 변경으로 인한 잘못된 값으로 요청. 지속될 경우 개발자에게 문의하세요.</li>
            </ul>
            <ul v-else-if="frame.error.detail.includes('50')">
                <li>서버가 불안정합니다. 페이지를 다시 고쳐보세요.</li>
                <li>서버 구조 변경으로 인한 내용 해석 실패. 지속될 경우 개발자에게 문의하세요.</li>
                <li>네트워크 방화벽에 의해 차단되지는 않았는지 확인해보세요.</li>
            </ul>
            <ul v-else>
                <li>알 수 없는 오류입니다. 아래 코드를 복사하여 개발자에게 문의해주세요.</li>
            </ul>
            <br/>
            <span class="refresher-mute">{{ frame.error.detail }}</span>
            <br/>
            <br/>
            <PreviewButton
                id="refresh"
                :click="retry"
                class="refresher-writecomment primary"
                text="다시 시도"
            />
        </div>
        <div v-else>
            <div class="refresher-preview-info">
                <div class="refresher-preview-title-zone">
                    <div
                        :class="{
                            'refresher-preview-title-text': true,
                            'refresher-title-post': frame.data.buttons
                        }"
                    >
                        <transition
                            appear
                            name="refresher-slide-up"
                            @enter="onEnter"
                            @before-enter="beforeEnter"
                        >
                            <div
                                :key="frame.title"
                                :data-index="index + 1"
                                class="refresher-preview-title"
                                v-html="frame.title"
                            />
                        </transition>
                        <transition
                            appear
                            name="refresher-slide-up"
                            @enter="onEnter"
                            @before-enter="beforeEnter"
                        >
                            <span
                                class="refresher-preview-title-mute"
                                v-html="frame.subtitle"
                            />
                        </transition>
                    </div>

                    <div
                        v-if="frame.data.comments"
                        class="refresher-comment-controls-container"
                    >
                        <template v-if="frame.data.useWriteComment">
                            <PreviewButton
                                id="write"
                                :click="toCommentWrite"
                                class="refresher-comment-controls"
                                text="댓글 쓰기"
                            />
                        </template>

                        <PreviewButton
                            id="refresh"
                            :click="refresh"
                            class="refresher-comment-controls"
                            text="새로고침"
                        />
                    </div>
                </div>

                <div class="refresher-preview-meta">
                    <User
                        v-if="frame.data.user"
                        :user="frame.data.user"
                    />

                    <div class="float-right">
                        <div class="date-views">
                            <TimeStamp
                                v-if="frame.data.date"
                                :date="frame.data.date"
                            />
                            <span
                                class="refresher-views"
                                v-text="frame.data.views"
                            />
                        </div>
                        <CountDown
                            v-if="frame.data.expire"
                            :date="frame.data.expire"
                        />
                    </div>
                </div>
            </div>

            <div
                v-if="frame.collapse"
                class="refresher-preview-contents"
            >
                <div class="refresher-collapse-text">
                    <h3
                        @click="
                            () => {
                                frame.collapse = false;
                                frame.functions.load();
                            }
                        "
                    >
                        댓글 보기를 클릭하여 댓글만 표시합니다. 여기를 눌러 글을 볼 수 있습니다.
                    </h3>
                </div>
            </div>
            <div
                v-else
                class="refresher-preview-contents"
            >
                <RefresherLoader
                    v-show="(frame.data.comments && (!frame.data.comments.comments || frame.data.comments.comments.length === 0)) && frame.data.load"/>

                <transition
                    v-if="!frame.data.comments"
                    name="refresher-opacity"
                >
                    <div
                        :class="
                            frame.data.useImageBlock &&
                            frame.data.type === 'icon_txt' &&
                            'refresher-preview-block-media'
                        "
                        class="refresher-preview-contents-actual"
                        v-html="frame.contents"
                    />
                </transition>
                <div v-else>
                    <div v-if="!frame.data.comments.comments || frame.data.comments.comments.length === 0">
                        <div class="refresher-nocomment-wrap">
                            <h3>댓글이 없습니다.</h3>
                        </div>
                    </div>
                    <div
                        v-else
                        class="refresher-preview-comments"
                    >
                        <transition-group
                            :key="commentKey"
                            appear
                            name="refresher-slide-up"
                            @enter="onEnter"
                            @before-enter="beforeEnter"
                        >
                            <Comment
                                v-for="(comment, i) in frame.data.comments.comments"
                                :key="comment.no"
                                v-model:reply="reply"
                                :comment="comment"
                                :delete="frame.functions.deleteComment"
                                :index="i + 1"
                                :post-user="frame.data.postUserId"
                                :use-write-comment="frame.data.useWriteComment"
                            />
                        </transition-group>
                    </div>

                    <div v-if="frame.data.useWriteComment">
                        <WriteComment
                            v-model:reply="reply"
                            :func="writeComment"
                            :get-big-dccon="getBigDccon"
                            :get-dccon="getDccon"
                            :renderDcconPopup="renderDcconPopup"
                            @setBigDccon="setBigDccon"
                            @setDccon="setDccon"
                        />
                    </div>
                </div>
            </div>
            <div
                v-if="frame.data.comments === undefined && frame.data.buttons"
                class="refresher-preview-votes"
            >
                <div>
                    <PreviewButton
                        id="upvote"
                        :click="upvote"
                        :text="
                            frame.upvotes === undefined && frame.fixedUpvotes === undefined
                                ? 'X'
                                : `${frame.upvotes} (${frame.fixedUpvotes})`
                        "
                        class="refresher-upvote"
                    />
                    <PreviewButton
                        v-if="!frame.data.disabledDownvote"
                        id="downvote"
                        :click="downvote"
                        :text="frame.downvotes ?? 'X'"
                        class="refresher-downvote"
                    />
                    <PreviewButton
                        id="share"
                        :click="share"
                        class="refresher-share primary"
                        text="공유"
                    />
                    <PreviewButton
                        id="newtab"
                        :click="original"
                        text="원본 보기"
                    />
                </div>
            </div>
        </div>
    </div>
</template>

<script lang="ts" setup>
import {createApp, onBeforeUnmount, onMounted, ref} from "vue";

import Comment from "./comment.vue";
import CountDown from "./countdown.vue";
import RefresherDcconPopup from "./dccon.vue";
import RefresherLoader from "./loader.vue";
import PreviewButton from "./previewButton.vue";
import TimeStamp from "./timestamp.vue";
import User from "./user.vue";
import WriteComment from "./write_comment.vue";

interface Props {
    frame: RefresherFrame;
    index: number;
}

const props = defineProps<Props>();

const reply = ref({
    commentNo: null as string | null,
    replyNo: null as string | null
});
const dccon = ref<DcinsideDccon[]>([]);
const bigDccon = ref(false);
const dcconRender = ref<any>(null);
const dcconApp = ref<any>(null);
const commentKey = ref(0);

const beforeEnter = (el: HTMLElement) => {
    el.style.transitionDelay = `${45 * Number(el.dataset.index)}ms`;
};

const onEnter = (el: HTMLElement) => {
    el.style.transitionDelay = "";
};

const upvote = () => {
    return props.frame.functions.vote(1);
};

const downvote = () => {
    return props.frame.functions.vote(0);
};

const share = () => {
    return props.frame.functions.share();
};

const retry = () => {
    return props.frame.functions.retry(false);
};

const writeComment = async (...args: any[]) => {
    try {
        await props.frame.functions.writeComment(...args);
        retry();
        return true;
    } catch {
        return false;
    }
};

const toCommentWrite = () => {
    document.querySelector<HTMLElement>("#comment_main")?.focus();
    return true;
};

const refresh = () => {
    retry();
    return true;
};

const renderDcconPopup = () => {
    if (dcconApp.value) return false;

    const element = document.createElement("div");
    document.body.appendChild(element);

    const app = createApp(RefresherDcconPopup, {
        onClickDccon: clickDccon,
        onCloseDccon: closeDccon
    });

    dcconApp.value = app;
    dcconRender.value = app.mount(element);

    return true;
};

const clickDccon = (selectedDccon: DcinsideDccon[], selectedBigDccon: boolean) => {
    dccon.value = selectedDccon;
    bigDccon.value = selectedBigDccon;
    closeDccon();
};

const closeDccon = () => {
    if (!dcconApp.value) return;

    dcconApp.value.unmount();
    dcconApp.value = null;
    dcconRender.value = null;
};

const setDccon = (value: DcinsideDccon[]) => {
    dccon.value = value;
};

const setBigDccon = (value: boolean) => {
    bigDccon.value = value;
};

const getDccon = () => {
    return dccon.value;
};

const getBigDccon = () => {
    return bigDccon.value;
};

const original = () => {
    props.frame.functions.openOriginal();
    return true;
};

onMounted(() => {
    props.frame.app.$on("close", () => {
        props.frame.title = "";
        props.frame.subtitle = "";
        props.frame.contents = undefined;
        props.frame.upvotes = undefined;
        props.frame.fixedUpvotes = undefined;
        props.frame.downvotes = undefined;
        props.frame.error = undefined;
        props.frame.collapse = undefined;
        props.frame.data = {};
        props.frame.functions = {};
        reply.value = {
            commentNo: null,
            replyNo: null
        };
        dccon.value = [];
        bigDccon.value = false;
        closeDccon();
        commentKey.value = 0;
    });
});

onBeforeUnmount(() => {
    closeDccon();
});

const incrementCommentKey = () => {
    commentKey.value++;
};

defineExpose({
    commentKey,
    incrementCommentKey
});
</script>

<style lang="scss">
$shadow-0dp: none;
$shadow-1dp: 0px 0px 16px rgba(0, 0, 0, 0.08);
$shadow-2dp: 0px 0px 16px rgba(0, 0, 0, 0.12);
$shadow-3dp: 0px 0px 16px rgba(0, 0, 0, 0.24);

.refresher-frame {
    background-color: #fff;
    border-radius: 13.3px;
    box-shadow: $shadow-2dp;
    display: block;
    max-width: 700px;
    min-height: 100px;
    min-width: 100px;
    overflow: hidden;
    padding: 3vh 2.5vw;
    pointer-events: all;
    position: absolute;
    transform: translateY(10px);
    width: 70%;

    @media screen and (max-width: 900px) {
        max-width: 90%;
        padding: 3vh 4vw;
    }

    &.blur {
        backdrop-filter: blur(5px) saturate(150%);
        background-color: rgba(245, 245, 245, 0.85);
    }

    &.center {
        margin: auto;
    }

    &.preview {
        min-height: 100px;
        min-width: 30vw;
    }

    &.relative {
        margin-bottom: 10px;
        position: relative;
    }

    &.x-center {
        margin-left: auto;
        margin-right: auto;
    }

    &.y-center {
        margin-bottom: auto;
        margin-top: auto;
    }
}
</style>
