// src/components/loader.tsx
import "./loader.scss";

export default function Loader() {
    return (
        <div className="refresher-loader spinner">
            {Array.from({length: 12}, (_, i) => (
                <div
                    className="spinner-blade"
                    key={i}
                />
            ))}
        </div>
    );
}

// src/components/loader.vue
<template>
    <transition name="refresher-opacity">
        <div class="refresher-loader spinner gray animating">
            <div class="spinner-blade" />
            <div class="spinner-blade" />
            <div class="spinner-blade" />
            <div class="spinner-blade" />
            <div class="spinner-blade" />
            <div class="spinner-blade" />
            <div class="spinner-blade" />
            <div class="spinner-blade" />
            <div class="spinner-blade" />
            <div class="spinner-blade" />
            <div class="spinner-blade" />
            <div class="spinner-blade" />
        </div>
    </transition>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
    name: "refresher-loader"
});
</script>
