// src/components/user.vue
<template>
    <div
        :class="{ cursor: !!this.user.id }"
        :data-me="me"
        :title="title"
        class="refresher-user"
        @click="clickHandle"
        @contextmenu="contextMenu">
        <div class="refresher-user-content">
            <span
                :data-icon="user.icon"
                :data-type="user.type"
                class="refresher-user-icon"/>
            <span class="refresher-user-nick">{{ user.nick }}</span>
            <span
                v-if="user.memo"
                :style="{ color: user.memo.color }"
                class="refresher-user-memo"
            >[{{ user.memo.text }}]</span
            >
            <span class="refresher-user-info">{{ userInfo }}</span>
        </div>
    </div>
</template>

<script lang="ts">
import {eventBus} from "../core/eventbus";
import Vue, {PropType} from "vue";
import {User} from "../utils/user";

export default Vue.extend({
    name: "refresher-user",
    props: {
        user: {
            type: Object as PropType<User>,
            required: true
        },

        me: {
            type: Boolean,
            required: false
        },

        click: {
            type: Function
        }
    },
    computed: {
        title(): string {
            if (this.user.isMember()) {
                const ratio = this.user.getRatio();
                return `(${this.user.id})${ratio ? ` [${ratio}]` : ""}`;
            }

            return `(${this.user.ip})${this.user.ip_data ? ` [${this.user.ip_data}]` : ""}`;
        },

        userInfo(): string {
            if (this.user.isMember()) {
                const ratio = this.user.getRatio();
                return `(${this.user.id})${ratio ? ` [${ratio}]` : ""}`;
            }

            return `(${this.user.ip})${this.user.ip_data ? ` [${this.user.ip_data}]` : ""}`;
        },
    },
    methods: {
        openLink(url: string): void {
            window.open(url, "_blank");
        },

        clickHandle(): void {
            if (typeof this.click === "function") {
                this.click(this.user);
                return;
            }

            if (this.user.id)
                this.openLink(
                    `https://gallog.dcinside.com/${this.user.id}`
                );
        },

        contextMenu(): void {
            eventBus.emit(
                "refresherUserContextMenu",
                this.user.nick,
                this.user.id,
                this.user.ip,
                null,
                null
            );
        }
    }
});
</script>

// src/components/user.tsx
import eventBus from "@/core/eventbus";
import {User} from "@/utils/user";

import "./user.scss";

interface Props {
    user: User;
    me?: boolean;
    click?: (user: User) => void;
}

export default function UserComponent({user, me = false, click}: Props) {
    const userDescription = (() => {
        if (!user.id && !user.ip) return "";

        if (user.isMember()) {
            const ban = user.ban;
            const ratio = user.ratio;

            return `${ban ? `[${ban}] ` : ""}${ratio ? ` [${ratio}] ` : ""}(${user.id})`;
        }

        return `(${user.ip})${user.ip_data ? ` [${user.ip_data}]` : ""}`;
    })();

    const clickHandle = (): void => {
        if (typeof click === "function") {
            click(user);
            return;
        }

        if (user.id) {
            window.open(`https://gallog.dcinside.com/${user.id}`, "_blank");
        }
    };

    const contextMenu = (): void => {
        eventBus.emit("refresherUserContextMenu", user.nick, user.id, user.ip, null, null);
    };

    return (
        <div
            className={user.id ? "refresher-user cursor" : "refresher-user"}
            data-me={me}
            onClick={clickHandle}
            onContextMenu={contextMenu}
            title={userDescription}
        >
            <div className="refresher-user-content">
                <span
                    className="refresher-user-icon"
                    data-icon={user.icon}
                    data-type={user.type}
                />
                <span className="refresher-user-nick">{user.nick}</span>
                {user.memo && (
                    <span
                        className="refresher-user-memo"
                        style={{color: user.memo.color}}
                    >
                        [{user.memo.text}]
                    </span>
                )}
                {!(me && user.isLogout()) && (
                    <span className="refresher-user-info">
                        {userDescription}
                    </span>
                )}
            </div>
        </div>
    );
}
