// src/entrypoints/content/modules/preview/components/comment/write_comment.tsx
import {useContext, useState} from "react";

import toast from "@/utils/toast";
import PreviewButton from "@/components/previewButton";
import UserComponent from "@/components/user";

import {useCommentUser} from "../../composables/useCommentUser";
import {InputFocusContext} from "../frame/frameComponent";

import "./write_comment.scss";

interface Props {
    func?: (
        type: "text" | "dccon",
        memo: string | DcinsideDccon[],
        commentNo: string | null,
        replyNo: string | null,
        user: { name: string; pw?: string },
        bigDccon: boolean
    ) => Promise<boolean>;
    reply?: { commentNo: string | null; replyNo: string | null };
    renderDcconPopup?: () => boolean;
    getDccon?: () => DcinsideDccon[];
    getBigDccon?: () => boolean;
    onSetDccon: (dccons: DcinsideDccon[]) => void;
    onSetBigDccon: (value: boolean) => void;
    onUpdateReply: (reply: { commentNo: string | null; replyNo: string | null }) => void;
}

export default function WriteComment({
    func,
    reply = {commentNo: null, replyNo: null},
    renderDcconPopup,
    getDccon,
    getBigDccon,
    onSetDccon,
    onSetBigDccon,
    onUpdateReply
}: Props) {
    const {
        user,
        unsignedUserID,
        unsignedUserPW,
        changeUnsignedUserID,
        changeUnsignedUserPW,
        fixedUser,
        editUser,
        toggleEditUser,
        validCheck
    } = useCommentUser();

    const [focused, setFocused] = useState(false);
    const [disabled, setDisabled] = useState(false);
    const [text, setText] = useState("");
    const [hoverUserInfo, setHoverUserInfo] = useState(false);

    const inputFocus = useContext(InputFocusContext);

    const dcconCount = getDccon?.().length ?? 0;

    const write = async (): Promise<boolean> => {
        setDisabled(true);

        if (!fixedUser && (!unsignedUserID || !unsignedUserPW)) {
            toast.show("아이디 혹은 비밀번호를 입력하지 않았습니다.", "error");
            setDisabled(false);
            return false;
        }

        if (!func) {
            setDisabled(false);
            return true;
        }

        const dccons = getDccon?.() ?? [];
        const bigDccon = getBigDccon?.() ?? false;

        try {
            const result = await func(
                dccons.length > 0 ? "dccon" : "text",
                dccons.length > 0 ? dccons : text,
                reply?.commentNo ?? null,
                reply?.replyNo ?? null,
                fixedUser && user
                    ? {name: user.nick}
                    : {
                        name: unsignedUserID,
                        pw: unsignedUserPW
                    },
                bigDccon
            );

            if (!result) {
                return false;
            }

            setText("");

            onSetDccon([]);
            onSetBigDccon(false);
            onUpdateReply({commentNo: null, replyNo: null});

            return result;
        } finally {
            setDisabled(false);
        }
    };

    const focus = (): void => {
        setFocused(true);
        inputFocus.current = true;
    };

    const blur = (): void => {
        setFocused(false);
        inputFocus.current = false;
    };

    const onKeyDown = (ev: React.KeyboardEvent): void => {
        if (ev.key === "Enter" && !ev.shiftKey) void write();
    };

    return (
        <div className="refresher-write-comment">
            <form
                className="user"
                onSubmit={(ev) => ev.preventDefault()}
                style={{display: editUser ? undefined : "none"}}
            >
                <input
                    onChange={(ev) => {
                        changeUnsignedUserID(ev.target.value);
                        validCheck("id", ev.target.value);
                    }}
                    placeholder="닉네임"
                    type="text"
                    value={unsignedUserID}
                />
                <input
                    onChange={(ev) => {
                        changeUnsignedUserPW(ev.target.value);
                        validCheck("pw", ev.target.value);
                    }}
                    placeholder="비밀번호"
                    type="password"
                    value={unsignedUserPW}
                />
            </form>
            <div className="refresher-comment-body">
                <div className={focused ? "refresher-input-wrap focus" : disabled ? "refresher-input-wrap disable" : "refresher-input-wrap"}>
                    <textarea
                        autoComplete="new-password"
                        disabled={disabled || dcconCount > 0}
                        id="comment_main"
                        onBlur={blur}
                        onChange={(ev) => setText(ev.target.value)}
                        onFocus={focus}
                        onKeyDown={onKeyDown}
                        placeholder={dcconCount > 0 ? "디시콘이 선택됐습니다." : "댓글 입력..."}
                        value={text}
                    />
                </div>
                <PreviewButton
                    className="refresher-writecomment"
                    click={() => renderDcconPopup?.() ?? false}
                    id="dccon"
                />
                <PreviewButton
                    className="refresher-writecomment"
                    click={write}
                    id="write"
                />
            </div>
            <div
                onMouseLeave={() => setHoverUserInfo(false)}
                onMouseOver={() => setHoverUserInfo(true)}
            >
                <div className={!(hoverUserInfo && !user?.id) ? "whoami refresher-comment-util refresher-comment-util-show" : "whoami refresher-comment-util"}>
                    {user && (
                        <UserComponent
                            me={true}
                            user={user}
                        />
                    )}
                    <span>로 {reply?.commentNo ? "답글" : ""} {dcconCount > 0 ? "디시콘" : ""} 작성 중</span>
                </div>
                <div className={hoverUserInfo && user?.isLogout() ? "whoami refresher-comment-util refresher-comment-util-edit refresher-comment-util-show" : "whoami refresher-comment-util refresher-comment-util-edit"}>
                    <span onClick={toggleEditUser}>
                        클릭하면 작성자 정보 수정 모드를 {editUser ? "비활성화" : "활성화"}시킵니다.
                    </span>
                </div>
            </div>
        </div>
    );
}

// src/components/write_comment.vue
<template>
    <div class="refresher-write-comment">
        <div
            v-show="editUser"
            class="user"
        >
            <input
                v-model="unsignedUserID"
                placeholder="닉네임"
                type="text"
                @change="(v) => validCheck('id', v.target.value)"
            />
            <div />
            <input
                v-model="unsignedUserPW"
                placeholder="비밀번호"
                type="password"
                @change="(v) => validCheck('pw', v.target.value)"
            />
        </div>
        <div class="refresher-comment-body">
            <div
                :class="{ focus: focused, disable: disabled }"
                class="refresher-input-wrap"
            >
                <textarea
                    id="comment_main"
                    :disabled="disabled || getDccon().length > 0"
                    :placeholder="!getDccon().length ? '댓글 입력...' : '디시콘이 선택됐습니다.'"
                    autocomplete="new-password"
                    @blur="blur"
                    @focus="focus"
                    @input="updateText"
                    @keydown="type"
                />
            </div>
            <PreviewButton
                id="write"
                :click="write"
                class="refresher-writecomment primary"
                text="작성"
            />
        </div>
        <div
            @mouseleave="hoverUserInfo = false"
            @mouseover="hoverUserInfo = true"
        >
            <div
                :class="{
                    'refresher-comment-util': true,
                    'refresher-comment-util-show': !(hoverUserInfo && !user.id)
                }"
                class="whoami"
            >
                <UserComponent
                    v-if="user"
                    :me="true"
                    :user="user"
                />
                <span>로 {{ reply.commentNo ? "" : "답글" }} {{ !getDccon().length ? "" : "디시콘" }} 작성 중</span>
            </div>
            <div
                :class="{
                    'refresher-comment-util': true,
                    'refresher-comment-util-edit': true,
                    'refresher-comment-util-show': hoverUserInfo && user.isLogout()
                }"
                class="whoami"
            >
                <span @click="toggleEditUser">
                    클릭하면 작성자 정보 수정 모드를 {{ editUser ? "비활성화" : "활성화" }}시킵니다.
                </span>
            </div>
        </div>
    </div>
</template>

<script lang="ts" setup>
import $ from "cash-dom";
import { getCurrentInstance, onMounted, ref, watch } from "vue";

import { Nullable } from "../utils/types";
import { User } from "../utils/user";
import PreviewButton from "./previewButton.vue";
import toast from "../utils/toast";
import UserComponent from "./user.vue";

interface Props {
    func?: (...args: any[]) => Promise<boolean>;
    reply?: { commentNo: string | null; replyNo: string | null };
    getDccon?: () => any[];
    getBigDccon?: () => boolean;
}

const props = withDefaults(defineProps<Props>(), {
    func: undefined,
    reply: () => ({ commentNo: null, replyNo: null }),
    getDccon: () => () => [],
    getBigDccon: () => () => false
});

const emit = defineEmits<{
    setDccon: [dccons: any[]];
    setBigDccon: [value: boolean];
    "update:reply": [reply: { commentNo: string | null; replyNo: string | null }];
}>();

// Reactive data
const focused = ref(false);
const disabled = ref(false);
const text = ref("");
const editUser = ref(false);
const fixedUser = ref(false);
const hoverUserInfo = ref(false);
const user = ref<Nullable<User>>(null);
const unsignedUserID = ref(localStorage.nonmember_nick || "ㅇㅇ");
const unsignedUserPW = ref(localStorage.nonmember_pw || Math.random().toString(36).substring(5));

// Get current instance for accessing root data
const instance = getCurrentInstance();

// Watchers
watch(unsignedUserID, (value: string) => {
    if (!user.value) return;

    localStorage.setItem("nonmember_nick", value);
    user.value.nick = value;
});

watch(unsignedUserPW, (value: string) => {
    localStorage.setItem("nonmember_pw", value);
});

// Lifecycle
onMounted(() => {
    const gallogName = document.querySelector("#login_box > .user_info .nickname > em");
    const fixedName = gallogName && gallogName.innerHTML ? gallogName.innerHTML : null;

    if (fixedName) {
        fixedUser.value = true;

        const gallogIcon = document.querySelector("#login_box > .user_info > .writer_nikcon");
        if (gallogIcon) {
            const attribute = gallogIcon.getAttribute("onclick");
            if (attribute) {
                const match = /window\.open\('\/\/gallog\.dcinside\.com\/(\w*)'\);/.exec(attribute);
                if (match && match[1]) {
                    const id = match[1];
                    const imgElement = gallogIcon.querySelector("img");
                    const src = imgElement ? imgElement.src : null;
                    user.value = new User(fixedName, id, null, src);
                }
            }
        }
    } else {
        user.value = new User(unsignedUserID.value, null, "127.0.0.1", null);
    }
});

// Methods
const updateText = (ev: InputEvent) => {
    text.value = (ev.target as HTMLTextAreaElement).value;
};

const validCheck = (type: string, value: string): void => {
    if (type === "id" && value.length < 1) {
        toast.show(`아이디는 최소 1자리 이상이어야 합니다. 자동으로 "ㅇㅇ"로 설정합니다.`);
        unsignedUserID.value = "ㅇㅇ";
    }

    if (type === "pw" && value.length < 2) {
        const random = Math.random().toString(36).substring(5);

        toast.show(`비밀번호는 최소 2자리 이상이어야 합니다. 자동으로 "${random}"로 설정합니다.`);
        unsignedUserPW.value = random;
    }
};

const toggleEditUser = (): void => {
    if (user.value && user.value.isLogout()) {
        editUser.value = !editUser.value;
    }
};

const write = async (): Promise<boolean> => {
    disabled.value = true;

    if (!fixedUser.value && (!unsignedUserID.value || !unsignedUserPW.value)) {
        toast.show("아이디 혹은 비밀번호를 입력하지 않았습니다.", "error");
        disabled.value = false;
        return false;
    }

    if (!props.func) return true;

    const dccons = props.getDccon ? props.getDccon() : [];
    const bigDccon = props.getBigDccon ? props.getBigDccon() : false;

    const result = await props.func(
        !dccons.length ? "text" : "dccon",
        dccons.length ? dccons : text.value,
        props.reply ? props.reply.commentNo : null,
        props.reply ? props.reply.replyNo : null,
        fixedUser.value && user.value
            ? { name: user.value.nick }
            : {
                  name: unsignedUserID.value,
                  pw: unsignedUserPW.value
              },
        bigDccon
    );

    if (!result) {
        disabled.value = false;
        return false;
    }

    disabled.value = false;

    text.value = "";
    $("#comment_main").val("");

    emit("setDccon", []);
    emit("setBigDccon", false);
    emit("update:reply", { commentNo: null, replyNo: null });

    return result;
};

const focus = (): void => {
    focused.value = true;
    if (
        instance &&
        instance.root &&
        instance.root.$children &&
        instance.root.$children[0] &&
        instance.root.$children[0].$data
    ) {
        instance.root.$children[0].$data.inputFocus = true;
    }
};

const blur = (): void => {
    focused.value = false;
    if (
        instance &&
        instance.root &&
        instance.root.$children &&
        instance.root.$children[0] &&
        instance.root.$children[0].$data
    ) {
        instance.root.$children[0].$data.inputFocus = false;
    }
};

const type = (ev: KeyboardEvent): KeyboardEvent | void => {
    if (ev.shiftKey && ev.key === "Enter") {
        return ev;
    }

    if (ev.key !== "Enter") {
        return ev;
    }

    write();
};
</script>
