// src/views/Input.tsx
import React, {ChangeEvent, useCallback, useState} from "react";

export function Input({onChange, placeholder, module, id, value, disabled}: {
    onChange(module: string, key: string, value: unknown): void;
    placeholder: string;
    module: string;
    id: string;
    value: string;
    disabled: boolean;
}) {
    const [inputValue, setInputValue] = useState(value);

    const onInput = useCallback((ev: ChangeEvent<HTMLInputElement>) => {
        setInputValue(ev.target.value);
        onChange(module, id, ev.target.value);
    }, [inputValue]);

    return (
        <div className="refresher-input">
            <input
                onChange={onInput}
                type="text"
                placeholder={placeholder}
                value={inputValue}
                disabled={disabled}
            />
        </div>
    );
}

// src/views/components/input.vue
<template>
    <div class="refresher-input">
        <input type="text" :data-id="id" :data-module="modname" :placeholder="placeholder" :value="value" :disabled="disabled" v-on:change="update"/>
    </div>
</template>

<script>
export default {
    name: "refresher-input",

    props: {
        change: {
            type: Function
        },

        placeholder: {
            type: String,
            required: false
        },

        modname: {
            type: String
        },

        id: {
            type: String
        },

        value: {
            type: String
        },

        disabled: {
            type: Boolean
        }
    },

    methods: {
        update(ev) {
            if (this.change) {
                this.change(
                    ev.target.dataset.module,
                    ev.target.dataset.id,
                    ev.target.value
                );
            }
        }
    }
};
</script>
